ustudio/storage

README.md
setup.py
storage/storage.py
tests/test_storage.py

@ustudio/dev   please review...
- add support for retrieving a `get_download_url()` to
- swift / cloudfiles / hpcloud storage objects
- supports specifying `temp_url_key=` query param
- local / ftp / ftps storage objects
- supports specifying `download_url_base=` query param
- updated `README.md` with documentation
- updated `setup.py`
- bumps `object_storage` version to 0.4.2

Add get_download_url to object_storage library

---

README.md
setup.py
storage/storage.py
tests/test_storage.py

@ustudio/dev  please review...
- `get_download_url()` should have been `get_temp_url()`
- bumped version to 0.5.1
- 0.5.0 should have been the previous change with new feature
- this fix would make it 0.5.1

fixed reference to misnamed pyrax function

---

README.md
setup.py
storage/storage.py
tests/test_storage.py

@ustudio/dev  please review...
- modified `get_download_url()` to urlencode filenames containing
spaces in them.  this is done AFTER the temp url is returned
from pyrax because `pyrax.get_temp_url()` uses the original
filename in signing the generated temp url.
- bumped version number for storage library

Fix `get_download_url()` to urlencode filenames with spaces

---

README.md
requirements.txt
setup.py
storage/storage.py
tests/test_storage.py

@ustudio/dev please review
- adds `s3` support to storage library
- all methods except for `get_download_url()` are covered
- bumps version number (in `setup.py` and `README.md` to 0.6.0)
**NOTE:**
Did not document the `?region=` query parameter availability since it appears that S3 does not require a region to be specified.  In fact, when I attempted to use `boto3` while specifying a `region_name=` I got an error when trying to retrieve the `"s3"` resource.

S3 support

---

CONTRIBUTORS
storage/storage.py
tests/test_storage.py

I propose to add specific port management with the FTP(s) protocols.
ftp[s]://username:password@host:port/path/to/file
If missing, 21 value is taken by default.
Unittests added and all pass after modification
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ustudio/storage/26)

Add specific FTP port management

---

README.md
setup.py
storage/storage.py
tests/test_storage.py

@ustudio/dev please review
Updated storage library to (v0.7.3) support deleting directories loaded by `load_from_directory()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ustudio/storage/32)

play-1029 - storage library should delete directories

---

README.md
circle.yml
pyrax-requirements.txt
setup.py
storage/storage.py
tests/test_storage.py

This adds support for a default FTP timeout, so FTP transfers don't hang forever, as we have seen recently.
Note, there are still some weird dependency issues in CI that might need to get fixed, but I'd like to get the review of at least the code started.
@ustudio/dev Please review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ustudio/storage/34)

Enable ftp timeout

---

README.md
setup.py
storage/storage.py
tests/test_storage.py

Switched to using threads for CloudFiles/Swift authentication timeouts, so the storage library can be used from inside threads.
@ustudio/dev Please review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ustudio/storage/37)

Use threads instead of signals to implement timeout

---

README.md
setup.py
storage/storage.py
tests/test_storage.py

Calls to `load_from_directory` and `save_to_directory` have been encountering an increased number of failures recently when the directories being transferred contain a large number of files. I have added retries to the individual file uploads/downloads for the Swift, Cloudfiles, and S3 storage classes to try to reduce the impact of these failures.
Note that I did *not* add retry logic to the methods on the `FTPStorage` class as this would require a more significant change to the library, and because`load_from_directory` and `save_to_directory` are less frequently used with FTP.
@ustudio/dev Please review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ustudio/storage/38)

Retry individual file failures

---

README.md
circle.yml
pyrax-requirements.txt
setup.py
storage/storage.py
tests/test_storage.py

This enables TCP keepalive and the FTP command socket, to work around socket timeout issues in certain environments, when the transfer takes a long time, leaving the command socket idle.

Enable TCP Keepalive on FTP Command Sockets

---

README.md
pyrax-requirements.txt
setup.py

This just re-releases v0.12.0 with a new version number. After we released it, we thought there was an error that made it unusable, so we quickly deleted it from PyPI, to prevent any downstream projects from being affected. However, once we were able to debug the issue, it was discovered that it was not an issue with the storage library at all, so no changes needed to be made. However, we do need to bump the version, since 0.12.0 is "taken" at PyPI.
Also, while debugging, we discovered that the latest version of keyring stopped supporting Python2, so we need to force an older version when installing the dependencies for testing. (doesn't affect downstream projects).
@ustudio/reviewers Please review.

Re-release 0.12.0 as 0.12.1

---

README.md
setup.py
storage/google_storage.py
storage/swift_storage.py
tests/test_google_storage.py
tests/test_swift_storage.py

This PR fixes two separate bugs from the change to add Google Storage (combined in one PR for expediencies sake):
1. The GoogleStorage class wasn't correctly decoding the base64 credentials when the Storage URI was a unicode string. Note that this change should be forwards-compatible with Python3, as, there, base64 can decode unicode `str`s or `bytes`, and the encoding shouldn't matter, as base64 only allows ascii characters, anyway.
1. By upgrading to a newer version of `requests`, as required by the Google library, we exposed a bug in PyRax when extracting the Download URL Key from the account metadata, caused by non-lowercase HTTP Headers. This change manually extracts the download URL key metadata, correctly ignoring case.

Fix bugs from adding Google Storage

---

README.md
setup.py
storage/swift_storage.py
tests/test_swift_storage.py

When `requests` returns headers without lowercasing them, `pyrax` correctly *finds* the headers that start with `X-Account-Meta`, but it doesn't correctly remove that prefix from the header before returning the dictionary of account metadata.

Correctly work around PyRax bug with newer requests library

---

README.md
setup.py
storage/google_storage.py
tests/test_google_storage.py

We discovered an issue with deleting directories from google, where we call `list_blobs` with the wrong arguments, generating an error and causing the entire deletion to fail.
Also, we ported the fix for handling blob generation numbers changing between the list and the access from the `save_to_directory` implementation, since `delete_directory` could be subject to the same issue.

Fix Google delete_directory bugs

---

README.md
setup.py
storage/google_storage.py
tests/test_google_storage.py

This updates the `get_download_url` method for Google storage objects to make the resulting download URL set the `Content-Disposition` response header in order to instruct the browser to download the content instead of displaying it inline.

Set content disposition for download urls (v0.12)

---

README.md
setup.py
storage/google_storage.py
stubs/google/cloud/storage/blob.pyi
tests/service_test_case.py
tests/swift_service_test_case.py
tests/test_google_storage.py

This is essentially the same as #50 but for the master branch, where only Python 3 is supported.
In addition to the download URL update, this change also fixes the intermittent test failures we've been experiencing in the Swift storage implementation tests. The problem was that the fake Swift server wasn't reading the entire chunked transfer before closing the connection, so the client would occasionally encounter "Broken pipe" errors while trying to send the chunked transfer. I have updated the fake server to read the entire chunked transfer, including the terminating 0-byte chunk at the end.
Lastly, I split the single `event` used for signalling between threads in the service case helpers to make he code a little easier to understand and to avoid some unnecessary looping. …

Set content disposition for download urls (v0.13)

---

README.md
setup.py

PEP 561 requires a package to include a `py.typed` file in order to use the type annotations in consuming projects. This adds that file to make it compatible.

Make package PEP 561 compatible

---

README.md
setup.py
storage/ftp_storage.py
storage/local_storage.py
storage/s3_storage.py
storage/storage.py
storage/swift_storage.py
storage/url_parser.py
tests/test_ftp_storage.py
tests/test_google_storage.py
tests/test_local_storage.py
tests/test_s3_storage.py
tests/test_storage.py
tests/test_swift_storage.py
tests/test_url_parser.py

Add the ability for each backend to sanitize it's URI in such a way that is most appropriate for the way it encodes secret data. 
@ustudio/reviewers for your consideration.

[PLAY-2375] -- Python 2.7 Support: Sanitize Storage URIs

---

README.md
integration-tests.py
setup.py
storage/google_storage.py
storage/s3_storage.py
storage/storage.py
tests/helpers.py
tests/test_google_storage.py
tests/test_s3_storage.py
tests/test_storage.py

This PR implements the same changes as #56 but in the 0.12 branch, for projects still using Python 2.7.

Correctly set Content Type with Google Storage and Amazon S3 in 0.12 branch

---

.flake8
README.md
setup.py
storage/swift_storage.py
tests/test_swift_storage.py

Rackspace CloudFiles appears to no longer return the `application/directory` content type for directory placeholder objects. This PR updates the code to use the name of the object to determine if it is a placeholder object, in addition to the content type.
We also updated the test to be a little more representative of the actual behavior of the PyRax library.

Update Swift Storage to Correctly Handle Directory Placeholder Objects

---

README.md
setup.py
storage/swift_storage.py
tests/swift_service_test_case.py
tests/test_swift_storage.py

This implements the same fix as #58 , but for the Python 3 code, which uses `python-swiftclient` instead of `pyrax`.

Fix Swift save_to_directory for swiftclient based implementation

---

.circleci/config.yml
requirements.txt
tests/test_s3_storage.py
tests/test_swift_storage.py

The primary purpose of this PR was to update the CircleCI configuration file to use contexts for managing the credentials which are used to run the integration tests as well as to publish the package to PyPI on release. This will make managing those credentials easier, and also separates the credentials so that jobs only have access to what they need.
In order to not duplicate the changes to the environment variables between the different test configurations, we took advantage of CircleCI's "Reusable Config" feature to template the test job, so it only needs to be defined once, and can be used to run tests in different Python versions with minimal duplication.
Once we pushed the changes to Circle, we ran into several issues caused by changing build images, which caused us to upgrade some …

Use CircleCI Contexts for Credentials

---

README.md
mypy.ini
pyproject.toml
storage/__init__.py
storage/s3_storage.py
stubs/boto3/__init__.pyi
test_integration.py
tests/test_s3_storage.py

This PR adds support for accessing S3 buckets owned by third parties. It also adds a new way to specify credentials in S3 storage URIs, by putting JSON in the URI's username field and omitting a password. The JSON structure includes support for specifying a role that is to be assumed in order to access the bucket.
I have added a new integration test that exercises the new S3 storage URI with JSON credentials feature.

Support Third-Party S3 Bucket Access

---

README.md
pyproject.toml

This PR fixes a couple minor issues I discovered after publishing v0.15.0 to PyPI. In particular, PyPI wasn't recognizing the license correctly and it no longer linked back to the GitHub page.
In addition, I fixed some minor annoyances in the README. The build status badge was showing a broken image, so I updated it. The example `pip install` command was using the non-canonical package name containing an underscore, which I replaced with a dash. Finally, the README listed the wrong "current version" and indicated how to get legacy Python support, which I have removed.

Fix Package Issues

---

pyproject.toml
storage/s3_storage.py
stubs/boto3/session.pyi
stubs/botocore/client.pyi
stubs/botocore/config.pyi
test_integration.py
tests/test_s3_storage.py

This PR updates the `s3` storage protocol to enforce "v4" signatures when generating signed URLs via `get_download_url`. It appears that there are certain instances where `boto3` opts to use v2 signatures, but AWS requires v4 signatures, possibly related to having `us-east-1` as the default region for the authenticating user, but then accessing a bucket in another region which doesn't support v2 signatures.
I also added integration tests for generating download URLs, although the default configuration in CI wasn't initially failing. I only enabled the tests for AWS S3 (with and without JSON credentials) and Google Storage, as the other configurations aren't set up for download URLs.
The type annotations for the `Config` object in `botocore` were a little ambiguous. The documentation for …

Force V4 Signatures for S3 Download URLs

---

pyproject.toml
storage/s3_storage.py
stubs/botocore/session.pyi
tests/test_s3_storage.py

This PR updates the `save_to_directory` and `delete_directory` methods of the S3 storage object to correctly iterate over all the pages returned by `list_objects`, when an S3 directory contains more than 1000 objects.
In looking up the documentation, I noticed that there is a `list_objects_v2`, which is now recommended; however, the semantics are slightly different, depending on bucket configurations, so I opted not to switch to that. I attempted to use the `NextMarker` return value from the response to iterate over the pages. However, the documentation states that we have to pass a `Delimiter` and, when doing so, the listing is no longer recursive of the whole "directory." Instead, I iterate by using the last item in the `Contents`, which is documented to iterate over pages correctly. …

Correctly handle paginated responses from s3 when operating on directories
